apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  platforms: ["linux/amd64", "linux/arm64"]
  artifacts:
  - image: emailservice
    context: src/emailservice
    hooks:
      before:
        - command: ["cmd", "/C", "set GOPRIVATE=github.com/microfaults/* && go mod vendor"]
          os: [windows]
        - command: ["sh", "-c", "GOPRIVATE=github.com/microfaults/* go mod vendor"]
          os: [darwin, linux]
  - image: productcatalogservice
    context: src/productcatalogservice
    hooks:
      before:
        - command: ["cmd", "/C", "set GOPRIVATE=github.com/microfaults/* && go mod vendor"]
          os: [windows]
        - command: ["sh", "-c", "GOPRIVATE=github.com/microfaults/* go mod vendor"]
          os: [darwin, linux]
  - image: recommendationservice
    context: src/recommendationservice
    hooks:
      before:
        - command: ["cmd", "/C", "set GOPRIVATE=github.com/microfaults/* && go mod vendor"]
          os: [windows]
        - command: ["sh", "-c", "GOPRIVATE=github.com/microfaults/* go mod vendor"]
          os: [darwin, linux]
  - image: shoppingassistantservice
    context: src/shoppingassistantservice
    hooks:
      before:
        - command: ["cmd", "/C", "set GOPRIVATE=github.com/microfaults/* && go mod vendor"]
          os: [windows]
        - command: ["sh", "-c", "GOPRIVATE=github.com/microfaults/* go mod vendor"]
          os: [darwin, linux]
  - image: shippingservice
    context: src/shippingservice
    hooks:
      before:
        - command: ["cmd", "/C", "set GOPRIVATE=github.com/microfaults/* && go mod vendor"]
          os: [windows]
        - command: ["sh", "-c", "GOPRIVATE=github.com/microfaults/* go mod vendor"]
          os: [darwin, linux]
  - image: checkoutservice
    context: src/checkoutService
    hooks:
      before:
        - command: ["cmd", "/C", "set GOPRIVATE=github.com/microfaults/* && go mod vendor"]
          os: [windows]
        - command: ["sh", "-c", "GOPRIVATE=github.com/microfaults/* go mod vendor"]
          os: [darwin, linux]
  - image: paymentservice
    context: src/paymentservice
    hooks:
      before:
        - command: ["cmd", "/C", "set GOPRIVATE=github.com/microfaults/* && go mod vendor"]
          os: [windows]
        - command: ["sh", "-c", "GOPRIVATE=github.com/microfaults/* go mod vendor"]
          os: [darwin, linux]
  - image: currencyservice
    context: src/currencyservice
    hooks:
      before:
        - command: ["cmd", "/C", "set GOPRIVATE=github.com/microfaults/* && go mod vendor"]
          os: [windows]
        - command: ["sh", "-c", "GOPRIVATE=github.com/microfaults/* go mod vendor"]
          os: [darwin, linux]
  - image: cartservice
    context: src/cartservice/src
    docker:
      dockerfile: Dockerfile
    hooks:
      before:
        - command: ["cmd", "/C", "set GOPRIVATE=github.com/microfaults/* && go mod vendor"]
          os: [windows]
        - command: ["sh", "-c", "GOPRIVATE=github.com/microfaults/* go mod vendor"]
          os: [darwin, linux]
  - image: frontend
    context: src/frontend
    hooks:
      before:
        - command: ["cmd", "/C", "set GOPRIVATE=github.com/microfaults/* && go mod vendor"]
          os: [windows]
        - command: ["sh", "-c", "GOPRIVATE=github.com/microfaults/* go mod vendor"]
          os: [darwin, linux]
  - image: adservice
    context: src/adservice
    hooks:
      before:
        - command: ["cmd", "/C", "set GOPRIVATE=github.com/microfaults/* && go mod vendor"]
          os: [windows]
        - command: ["sh", "-c", "GOPRIVATE=github.com/microfaults/* go mod vendor"]
          os: [darwin, linux]
  tagPolicy:
    gitCommit: {}
  local:
    useDockerCLI: true
    useBuildkit: true
manifests:
  kustomize:
    paths:
    - kubernetes-manifests
deploy:
  kubectl: {}
